### ISSUE TITLE
Moving package to --setasreleased

### ISSUE THREAD

**Issue by jwsources** [heroku/salesforce-buildpack#24] opened 2018-04-09 10:41 UTC
Packages can't be installed on production without having a version:update with the --setareleased option. Currently the buildpack does the same package installation Dev, Staging and Prod. In a test scenario not using prod Orgs (Sandboxes) this works fine. However using a non-Sandbox as Prod Org doesn't install the package with the message: "Unable to install beta package". So Pipeline isn't doing fully automated deployment.
Will test with an additional step if STAGE = PROD to release the package, and create a pull request if successful.

**Comment by jwsources** [comment] 2018-04-11 07:38
Unable to test properly so not yet creating a pull request. My assumption is that I can't Release and Deploy on a production Org because of packaging not being GA.

**Comment by wadewegner** [comment] 2018-05-26 03:17
I don't follow. Using Unlocked Packages, you can install new versions of the package. The buildpack currently is not setup to use 1st Generation Managed Packages.

I'm going to close this issue. Please share details on what's not working if you're still having issues.

**Comment by douglascayers** [comment] 2018-05-26 04:04
Hi @wadewegner,

The issue is that by default new package versions start in a `beta` status, which are blocked from being installed in production environments. Beta package versions can only be installed in developer and sandbox environments.

That means that when trying to promote from `staging` to `production` (assuming your production stage is using an actual production salesforce org), then the package install fails with error:

```
       [DEBUG] CMD: sfdx force:package:install --noprompt -i "04tB000000069aNIAQ" -u "ra-bbeed7837202c848aaee019b2ad58cd4af78d5b2" --wait 1000 --publishwait 1000
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
ERROR:  Encountered errors installing the package!,Installation errors: 
1) Package(033B0000000MKzZ) Unable to install beta package, Details: The package you attempted to install is a beta package, which you can only install in Sandbox or Developer Edition organizations.
```

I think the fix here is when during the release phase, if the stage is production, then the buildpack marks the package version as released before attempting to install it.

**Comment by wadewegner** [comment] 2018-05-26 04:30
I see. Thanks for the thorough explanation. I should have remembered it is beta.

**Comment by wadewegner** [comment] 2018-05-26 04:44
It looks like this will have to use the `--setasreleased` option. Once it's set, though, it cannot be undone. Which is unfortunate, as there is no way in the pipeline to let people know.

**Comment by douglascayers** [comment] 2018-05-26 04:50
Yeah, the only way I could think of letting people know is they'd need to RTFM and the buildpack README be very clear about what happens in the "production" stage if deploying via packages.

**Comment by wadewegner** [comment] 2018-05-26 14:26
@DouglasCAyers @cwallsfdc @jwsources Take a look at https://github.com/heroku/salesforce-buildpack/pull/29. You could test by targeting the branch. I don't have a production org at the moment so don't have an easy way to verify.

**Comment by douglascayers** [comment] 2018-05-27 05:44
Thanks Wade, I needed to make some further changes after testing with a production org. Please see my pull request based on your branch, https://github.com/heroku/salesforce-buildpack/pull/30 Thanks!

**Comment by wadewegner** [comment] 2018-05-27 13:05
Thanks @DouglasCAyers! I merged your fix and addition into the PR and then into master. This time I double-checked and it's working as expected.

@jwsources Give it a shot. Be sure to add the `SFDX_DEV_HUB_AUTH_URL` to STAGING and PROD.

**Closed as completed by wadewegner** 2018-05-27 13:05 UTC
Labels: bug

**Comment by douglascayers** [comment] 2018-05-27 15:29
Woot! Thanks @wadewegner!
